import { Book } from "../types/book";

// Mock data for books
export const initialBooks: Book[] = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    description: `Vào những năm 1920 phồn hoa ở New York, Jay Gatsby là một nhân vật bí ẩn nổi bật giữa đám đông hào nhoáng. Mọi người đồn rằng anh ta giàu có vô song, tổ chức những bữa tiệc xa hoa, và dường như biết hết mọi bí mật trong giới thượng lưu. Tuy nhiên, ít ai biết rằng Gatsby chỉ là một chàng trai xuất thân khiêm tốn, mang trong mình khát khao mãnh liệt được tái lập mối tình đã mất với Daisy Buchanan, một người phụ nữ đã kết hôn với Tom, quý tộc cũ kĩ và giàu có.  
Trong suốt câu chuyện, thông qua ánh mắt của Nick Carraway — người hàng xóm và cũng là người kể chuyện — chúng ta thấy được sự tương phản gay gắt giữa vẻ hào nhoáng bề ngoài và những khoảng trống nội tâm: tình yêu mãnh liệt nhưng vô vọng, giấc mơ Mỹ nhưng đầy rẫy sự giả dối và bội phản. Fitzgerald khéo léo vẽ nên một bức tranh xã hội đầy màu sắc nhưng cũng đầy bi kịch của kỷ nguyên Roaring Twenties, nơi tiền bạc và danh vọng lên ngôi, trong khi giá trị con người dễ dàng bị đánh đổi. Cuốn tiểu thuyết không chỉ là câu chuyện cá nhân của Gatsby, mà còn là lời cảnh tỉnh về cái giá của giấc mơ không tưởng và sự mong manh của hạnh phúc thực sự.`,
    price: 180000,
    coverImage: "/images/books/the-great-gatsby.jpg",
    isbn: "978-0743273565",
    category: "Văn học",
    publishYear: 1925,
    stock: 40,
  },
  {
    id: "2",
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    description: `Trong thung lũng hẻo lánh Macondo, gia tộc Buendía trải qua hơn một thế kỷ với vô vàn những câu chuyện kỳ ảo xen lẫn thực tại. Từ khi José Arcadio Buendía và người vợ Úrsula Iguarán đặt những viên gạch đầu tiên xây nên thị trấn đến lúc những lời tiên tri và lời nguyền bên dòng họ dường như trở thành hiện thực, Marquez khéo léo dệt nên tấm thảm thời gian nơi quá khứ, hiện tại và tương lai đan xen chặt chẽ.  
Mỗi nhân vật trong gia đình Buendía đều mang một dòng máu mang tính định mệnh: dục vọng, sự cô đơn, khát khao khám phá và nỗi sợ hãi trước cái chết. Những chi tiết như những đứa trẻ sinh ra với đuôi lửng, những trận mưa lá vàng, và những lá thư không bao giờ đến tay người nhận tô điểm cho phong cách “hiện thực huyền ảo” độc đáo. Cuốn sách là bản trường ca về vòng lặp của lịch sử, về cách con người luôn tìm kiếm ý nghĩa trong những chu kỳ lặp lại, và cuối cùng phải đối mặt với sự vô thường của vận mệnh. Đây không chỉ là câu chuyện của một dòng họ, mà còn là tấm gương phản chiếu những giá trị, niềm đau và hy vọng chung của nhân loại.`,
    price: 220000,
    coverImage: "/images/books/one-hundred-years-of-solitude.jpg",
    isbn: "978-0060883287",
    category: "Hiện thực huyền ảo",
    publishYear: 1967,
    stock: 35,
  },
  {
    id: "3",
    title: "Khi trẻ người ta nghĩ khác",
    author: "Lê Khải Việt",
    description: `Ngay từ tác phẩm đầu tay mang tên Chuyến bay tháng 3, Lê Khải Việt đã để lại những dấu ấn độc đáo với cách viết mới lạ và đầy hấp dẫn. Từ sườn, cốt là những gì còn lại của một di sản chiến tranh khốc liệt, anh đã hình tượng và nâng cấp nhiều lớp để tạo nên những truyện ngắn hấp dẫn, ấn tượng, không thôi ám ảnh, cho thấy một sự kế thừa cũng như học hỏi từ các nhà văn nổi tiếng cả trong cũng như ngoài nước. Khi trẻ người ta nghĩ khác mở rộng phạm vi hơn so với Chuyến bay tháng 3 trước đó, khi dần tiến thêm vào sự đứt gãy những mối quan hệ của các cá nhân trong xã hội hiện đại, từ đó tạo nên những truyện ngắn tạo nhiều đồng cảm. Song song đó, chủ đề chiến tranh vẫn luôn hiện diện, cho thấy một nỗi ám ảnh của cây bút này.`,
    price: 112000,
    coverImage: "/images/books/nguoi-tre-nguoi-ta-nghi-khac.jpg",
    isbn: "978-0156453806",
    category: "Văn học",
    publishYear: 2024,
    stock: 30,
  },
  {
    id: "4",
    title: "The Master and Margarita",
    author: "Mikhail Bulgakov",
    description: `Cuốn tiểu thuyết mở đầu khi Giáo sư Woland – hóa thân của ma quỷ – cùng đoàn tùy tùng ghé thăm Moscow thập niên 1930, nơi chủ nghĩa vô thần được tôn sùng. Họ gây náo loạn trong giới văn nghệ sĩ và quan chức cấp cao, lật tẩy tham nhũng, giả dối và sự giả hình của xã hội Xô Viết :contentReference[oaicite:0]{index=0}. Song song đó, câu chuyện hồi tưởng về nhân vật ‘Master’, một nhà văn bất trị phải chịu cảnh trầm cảm, bỏ bút giữa chừng khi bị kiểm duyệt, và Margarita – người tình say đắm, sẵn sàng hy sinh để cứu tình yêu và tác phẩm của Master. Hành trình của Margarita vào đêm hội Good Friday tại cung điện Satan, khả năng “bay lượn” và lẽ sống được săn đuổi, tất cả đều đan xen sự hài hước đen tối với triết lý về thiện – ác, tự do tinh thần và quyền lực của nghệ thuật :contentReference[oaicite:1]{index=1}. Cuốn sách vừa là bức tranh xã hội châm biếm sắc bén, vừa là khúc khải hoàn cho tình yêu và sự cứu rỗi tinh thần.`,
    price: 200000,
    coverImage: "/images/books/the-master-and-margarita.jpg",
    isbn: "978-0141180144",
    category: "Hư cấu siêu nhiên",
    publishYear: 1967,
    stock: 25,
  },
  {
    id: "5",
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    description: `Raskolnikov – một cựu sinh viên nghèo rơi vào khủng hoảng triết lý về “siêu nhân” và “tội ác vì mục đích cao cả” – quyết định giết và cướp của hai bà lão giàu có. Tuy nhiên, hậu quả tâm lý của hành vi lại đẩy anh vào vòng xoáy hối hận, tội lỗi và sợ hãi tột độ :contentReference[oaicite:2]{index=2}. Suốt câu chuyện, độc giả chứng kiến sự đấu tranh nội tâm dữ dội của Raskolnikov qua những cơn sốt mê sảng, giấc mơ ám ảnh, và các cuộc đối thoại với Porfiry – viên thanh tra tinh ranh. Bên cạnh đó, nhân vật Sonia – cô gái bán thân nhưng giàu lòng vị tha – trở thành nguồn cảm hứng để Raskolnikov tìm về niềm tin, nhận ra giá trị của tình người và sự chuộc tội :contentReference[oaicite:3]{index=3}. Dostoevsky vừa khắc họa sâu sắc tội ác và hình phạt, vừa đặt ra câu hỏi về lương tâm, đức tin và ý nghĩa của sự cứu rỗi.`,
    price: 190000,
    coverImage: "/images/books/crime-and-punishment.jpg",
    isbn: "978-0143058144",
    category: "Tiểu thuyết",
    publishYear: 1866,
    stock: 30,
  },
  {
    id: "6",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: `Elizabeth Bennet – thông minh, hài hước và có phần kiêu hãnh – chạm trán với ông Darcy kiệm lời nhưng đầy lòng tự trọng. Ban đầu, Elizabeth chê trách Darcy kiêu ngạo, trong khi Darcy bị thu hút bởi sự sắc sảo và chính trực của cô :contentReference[oaicite:4]{index=4}. Khi dần khám phá quá khứ của Darcy – bao gồm việc giúp đỡ em gái Elizabeth thầm lặng – cô nhận ra sự hiểu nhầm của mình, và chính cái gọi là “kiêu” cùng “định kiến” đã ngăn cản họ đến bên nhau. Austen khéo léo lồng vào mối quan hệ tình cảm ấy những bình luận châm biếm về hôn nhân, địa vị xã hội và vai trò phụ nữ nước Anh đầu thế kỷ 19 :contentReference[oaicite:5]{index=5}. Cuốn tiểu thuyết không chỉ là câu chuyện tình yêu, mà còn là bài học về lòng khiêm tốn, sự thấu hiểu và sức mạnh của thay đổi nhận thức.`,
    price: 170000,
    coverImage: "/images/books/pride-and-prejudice.jpg",
    isbn: "978-1503290563",
    category: "Tiểu thuyết",
    publishYear: 1813,
    stock: 45,
  },
  {
    id: "7",
    title: "The Catcher in the Rye",
    author: "J. D. Salinger",
    description: `Holden Caulfield – thiếu niên 16 tuổi – rời khỏi trường sau khi bị đuổi vì học kém và lang thang khắp New York suốt vài ngày trước Giáng sinh. Qua lăng kính hoài nghi và châm biếm, cậu bộc lộ nỗi cô đơn, thất vọng với “giả dối” của thế giới người lớn và khao khát bảo vệ sự vô tư của trẻ thơ :contentReference[oaicite:6]{index=6}. Mỗi cuộc gặp gỡ – từ cô gái điếm Sunny đến cô bạn cũ Sally Hayes – đều khơi gợi trong Holden những nỗi sợ lớn lên và đánh mất ngây thơ. Hắn mộng tưởng trở thành “người bắt ngô đồng”, cứu các trẻ con khỏi rơi khỏi vách đá của sự trưởng thành. Salinger tạo nên một lời độc thoại nội tâm chân thực, vang vọng tiếng nói của tuổi trẻ chống lại quy cách và bi kịch phải đối mặt với thế giới phức tạp.`,
    price: 160000,
    coverImage: "/images/books/the-catcher-in-the-rye.jpg",
    isbn: "978-0316769488",
    category: "Tiểu thuyết",
    publishYear: 1951,
    stock: 38,
  },
  {
    id: "8",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    description: `Qua ánh mắt của Scout Finch – cô bé sống ở Maycomb, Alabama thập niên 1930 – người đọc chứng kiến câu chuyện về công lý và phân biệt chủng tộc khi cha cô, luật sư Atticus Finch, bào chữa cho Tom Robinson, một người da đen bị vu oan hiếp dâm một phụ nữ da trắng . Xã hội lên án và đe dọa, nhưng Atticus kiên định theo đuổi sự thật, dạy cho Scout và người anh Jem bài học về lòng can đảm và lòng trắc ẩn. Bên cạnh vụ án, Lee khắc họa ký ức tuổi thơ hồn nhiên của Scout – những trò chơi, lén nhìn người hàng xóm bí ẩn Boo Radley, và dần nhận ra phức tạp trong tâm hồn con người. Cuốn sách là bức tranh nước Mỹ đầy mâu thuẫn, vừa lay động, vừa thôi thúc suy ngẫm về đạo đức và nhân quyền`,
    price: 175000,
    coverImage: "/images/books/to-kill-a-mockingbird.jpg",
    isbn: "978-0446310789",
    category: "Tiểu thuyết",
    publishYear: 1960,
    stock: 42,
  },
  {
    id: "9",
    title: "1984",
    author: "George Orwell",
    description: `London năm 1984 dưới chế độ toàn trị của “Big Brother”: mỗi cử chỉ, lời nói của công dân đều bị giám sát bởi Đảng Xô-viết. Winston Smith – một nhân viên Sở Lưu trữ – âm thầm chống lại hệ thống, ghi nhật ký phản kháng và mưu đồ kết nối với phe kháng chiến bí mật. Khi gặp Julia – đồng chí cùng chí hướng – họ trải qua mối tình nồng cháy, hy vọng vào sự thay đổi. Nhưng Đảng có khả năng thâm nhập sâu nhất vào tư tưởng, dùng máy nghe lén, “Tư tưởng cảnh sát” và Khoa Phục hồi Tư tưởng để bẻ gãy ý chí bất kỳ ai. Cuốn sách là lời cảnh báo về nguy cơ mất quyền tự do, sự xói mòn chân lý và sự tàn bạo của bạo quyền.`,
    price: 165000,
    coverImage: "/images/books/1984.jpg",
    isbn: "978-0451524935",
    category: "Khác",
    publishYear: 1949,
    stock: 50,
  },
  {
    id: "10",
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    description: `Amir – cậu bé con nhà giàu người Afghanistan – và Hassan, con trai người hầu, có mối quan hệ gắn bó qua trò đấu diều. Tuy nhiên, khi chứng kiến Hassan bị hãm hiếp, Amir sợ hãi và im lặng, dẫn đến đổ vỡ tình bạn và cảm giác tội lỗi dai dẳng suốt cuộc đời . Sau khi chạy trốn sang Mỹ, Amir trưởng thành, nhưng nỗi ám ảnh quá khứ khiến anh quay về Taliban–chiếm đóng Kabul để cứu con trai bé bỏng của Hassan và chuộc lỗi. Câu chuyện xen lẫn ký ức đẹp đẽ về tuổi thơ với những hình ảnh khốc liệt của chiến tranh, đan xen hy vọng và tha thứ. Hosseini khắc họa sâu sắc tình bạn, sự phản bội và hành trình chuộc tội vượt thời gian .`,
    price: 180000,
    coverImage: "/images/books/the-kite-runner.jpg",
    isbn: "978-1594631931",
    category: "Tiểu thuyết",
    publishYear: 2003,
    stock: 33,
  },
  {
    id: "11",
    title: "Đắc Nhân Tâm",
    author: "Dale Carnegie",
    description: `Cuốn sách kinh điển về kỹ năng giao tiếp và quản trị bản thân, đưa ra 30 nguyên tắc để thuyết phục, tạo thiện cảm và ảnh hưởng tích cực đến người khác. Carnegie dựa trên nhiều nghiên cứu tâm lý và hàng loạt ví dụ thực tiễn từ doanh nhân, chính trị gia và người nổi tiếng . Người đọc sẽ học cách lắng nghe chân thành, khen ngợi đúng lúc, tránh chỉ trích trực tiếp và giải quyết xung đột một cách khéo léo. Qua phương pháp ‘thấy được điểm mạnh của người khác’ và ‘kích thích khát khao bên trong’, cuốn sách không chỉ giúp cải thiện mối quan hệ cá nhân mà còn thúc đẩy sự nghiệp và lãnh đạo hiệu quả hơn.`,
    price: 99000,
    coverImage: "/images/books/dac-nhan-tam.jpg",
    isbn: "978-6047712345",
    category: "Kỹ năng sống",
    publishYear: 1936,
    stock: 50,
  },
  {
    id: "12",
    title: "Dế Mèn phiêu lưu ký",
    author: "Tô Hoài",
    description: `Tác phẩm kể câu chuyện về Dế Mèn – chú dế kiêu ngạo, ương bướng – từ khi tách ra khỏi tổ cưu mang, vướng vào hàng loạt cuộc phiêu lưu đầy gian nan. Từ cuộc chiến với dế Choắt, đến những ngày sống cùng Sáo Sậu, Dế Mèn học được bài học về tình bạn, lòng dũng cảm và sự khiêm tốn :contentReference[oaicite:15]{index=15}. Giọng văn của Tô Hoài giàu âm điệu dân gian, lồng ghép triết lý nhân sinh nhẹ nhàng, khiến độc giả nhỏ tuổi và người lớn đều say mê. Cuốn sách không chỉ là truyện thiếu nhi, mà còn là lời nhắc về trách nhiệm, tình thương và giá trị của mỗi cá thể trong xã hội.`,
    price: 85000,
    coverImage: "/images/books/de-men-phieu-luu-ky.jpg",
    isbn: "978-6049912341",
    category: "Văn học",
    publishYear: 1953,
    stock: 60,
  },
  {
    id: "13",
    title: "Số Đỏ",
    author: "Vũ Trọng Phụng",
    description: `Tiểu thuyết châm biếm xã hội Hà Nội thập niên 1930, xoay quanh anh chàng Xuân Tóc Đỏ – từ phường chèo lên giới thượng lưu chỉ nhờ may mắn và ‘chiêu trò’. Thông qua các nhân vật phong phú: bà lái buôn Nguyễn Cẩm Vân, ông chủ quán Ánh Cảnh, bác sĩ Stanley, Phương Bào… Phụng mổ xẻ những thói hư tật xấu của giới tư sản mới: giả dối, tầm thường, ham danh lợi :contentReference[oaicite:16]{index=16}. Lối kể nhanh, hài hước và ngôn ngữ chua chát giúp cuốn sách trở thành viên ngọc đen trong nền văn học hiện thực phê phán Việt Nam.`,
    price: 90000,
    coverImage: "/images/books/so-do.jpg",
    isbn: "978-6047701234",
    category: "Văn học",
    publishYear: 1936,
    stock: 55,
  },
  {
    id: "14",
    title: "Brave New World",
    author: "Aldous Huxley",
    description: `Khởi đầu trong thập niên 2540 của ‘Kỷ nguyên Phục hưng Xã hội’, thế giới được tổ chức theo mô hình ‘hạnh phúc tối đa’, nơi mọi công dân từ khi sinh ra đã được phân tầng gen, huấn luyện tâm lý và nhồi nhét tư tưởng để chấp nhận vai trò trong xã hội. Trái với những xưởng thụ tinh nhân tạo và những “hạt giống hoang” (những cá thể không thuộc bất kỳ tầng lớp nào), Bernard Marx – một Alpha có cơ thể yếu đuối – cảm thấy lạc lõng. Khi anh cùng Lenina Crowne tham quan khu “Dựng lại Con người”, gặp gỡ John ‘Người hoang dã’ – con trai của công dân Bắc Mỹ bị lưu đày, được nuôi dạy theo phong tục nguyên thủy, cả ba nảy sinh những nhận thức khác biệt. John đặt câu hỏi về tình yêu, nghệ thuật và khổ đau – những điều mà xã hội ‘Brave New World’ đã xóa bỏ. Huxley cảnh báo về việc đánh đổi tự do và chiều sâu cảm xúc để lấy ổn định và hưởng thụ ngắn hạn.`,
    price: 165000,
    coverImage: "/images/books/brave-new-world.jpg",
    isbn: "978-0060850524",
    category: "Khoa học viễn tưởng",
    publishYear: 1932,
    stock: 28,
  },
  {
    id: "15",
    title: "The Hobbit",
    author: "J. R. R. Tolkien",
    description: `Bilbo Baggins – chú hobbit hiền lành và yêu thích sự an nhàn – bỗng bị cuốn vào cuộc phiêu lưu cùng nhóm lùn của Thorin Oakenshield để tái chiếm vương quốc Erebor từ rồng Smaug. Qua rừng già, những quãng sông băng và thung lũng tối tăm, Bilbo phát hiện ra yêu tinh, trolls, và những con đường hầm nguy hiểm. Tại Gollum, Bilbo tình cờ tìm thấy chiếc nhẫn quyền năng cho phép trở nên vô hình, khởi nguồn cho câu chuyện thiên niên kỷ về Chúa tể của những Chiếc Nhẫn. Dưới ngòi bút của Tolkien, “The Hobbit” vừa là truyện phiêu lưu dành cho thiếu nhi, vừa mở ra một thế giới thần thoại sâu rộng, nơi mỗi sinh vật đều có nền văn hóa và lịch sử riêng. Hành trình của Bilbo là biểu tượng cho sự trưởng thành, khám phá bản thân và dũng khí tiềm ẩn trong mỗi con người.`,
    price: 185000,
    coverImage: "/images/books/the-hobbit.jpg",
    isbn: "978-0547928227",
    category: "Thần thoại & Phiêu lưu",
    publishYear: 1937,
    stock: 40,
  },
  {
    id: "16",
    title: "The Alchemist",
    author: "Paulo Coelho",
    description: `Santiago – chàng chăn cừu Tây Ban Nha – mơ thấy kho báu giấu dưới chân Kim Tự Tháp ở Ai Cập. Bị thôi thúc bởi niềm khao khát khám phá, cậu bán đàn cừu và lên đường qua những sa mạc khắc nghiệt, gặp gỡ những nhân vật định mệnh: một vị vua già dặn, một cậu bé bán đá pha lê, và cuối cùng là alchemist trong sa mạc Sahara. Mỗi bước đi đều chứa đựng bài học về “Ngôn ngữ của Vũ trụ”, nơi con người chỉ thực sự tìm thấy bản thân khi dám mơ và hành động vì giấc mơ. Coelho dùng giọng văn giản dị nhưng giàu triết lý, khiến độc giả tự vấn về phép màu trong cuộc sống hằng ngày và ý nghĩa của “vận mệnh cá nhân”.`,
    price: 150000,
    coverImage: "/images/books/the-alchemist.jpg",
    isbn: "978-0062315007",
    category: "Văn học",
    publishYear: 1988,
    stock: 37,
  },
  {
    id: "17",
    title: "Norwegian Wood",
    author: "Haruki Murakami",
    description: `Torū Watanabe – sinh viên đại học Tokyo thập niên 1960 – bị ám ảnh bởi cái chết của bạn thân Kizuki và mối quan hệ cùng Naoko, bạn gái cũ của Kizuki. Khi Naoko nhập trại điều trị tâm lý, Torū dấn thân vào đời sống sinh viên sôi động, gặp gỡ Midori – cô nàng hoạt bát, quyến rũ và đầy sức sống, khiến cậu phân vân giữa tình yêu với người cũ và thôi thúc khám phá cảm xúc mới. Murakami khéo léo kết hợp nỗi cô đơn, hoài niệm với hình ảnh âm nhạc Beatles, tạo nên không khí vừa lãng mạn vừa u tịch. Cuốn tiểu thuyết là hành trình đi tìm sự cân bằng giữa ký ức và hiện tại, giữa tình yêu và nỗi đau tâm lý.`,
    price: 170000,
    coverImage: "/images/books/norwegian-wood.jpg",
    isbn: "978-0375704024",
    category: "Tiểu thuyết",
    publishYear: 1987,
    stock: 32,
  },
  {
    id: "18",
    title: "Beloved",
    author: "Toni Morrison",
    description: `Sethe – người phụ nữ da màu bỏ trốn khỏi nô lệ – sống cùng con gái Denver trong ngôi nhà bị ám hồn ma đứa con đã mất tên ‘Beloved’. Khi một cô gái bí ẩn xuất hiện, khơi dậy ký ức kinh hoàng về Sweet Home – nông trại nô lệ nơi Sethe sinh con – quá khứ và hiện tại hòa quyện, kéo Sethe vào vòng xoáy tội lỗi và khao khát chuộc tội. Morrison dùng lối kể xen kẽ thì hiện tại và ký ức, ngôn ngữ nhiều lớp nghĩa, đan cài huyền ảo, phản ánh sức tàn phá của chế độ nô lệ lên tâm hồn con người. “Beloved” là bản cáo trạng đanh thép về quá khứ, đồng thời là thông điệp về sức mạnh tình mẫu tử và khát vọng tự do bất diệt.`,
    price: 195000,
    coverImage: "/images/books/beloved.jpg",
    isbn: "978-1400033416",
    category: "Văn học",
    publishYear: 1987,
    stock: 27,
  },
  {
    id: "19",
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    description: `Bắt đầu từ một phi công gặp trục trặc máy bay giữa sa mạc Sahara, “The Little Prince” là câu chuyện thần thoại về cậu bé hoàng tử đến từ hành tinh B612. Qua các chương ngắn, hoàng tử kể về chuyến thăm các hành tinh lân cận, gặp gỡ các người lớn kỳ quặc: vua tự phong, kẻ hợm hĩnh, doanh nhân săn sao, và cuối cùng là cô cáo dạy cậu bài học về tình yêu và trách nhiệm. Với nét vẽ ngộ nghĩnh và lời văn giản dị nhưng sâu sắc, Exupéry khám phá chủ đề cô đơn, ngây thơ và tình bạn bền vững. Đó là một tác phẩm vượt giới hạn tuổi tác, giáo dục về giá trị con tim và khả năng nhìn thấy những điều vô hình bằng trái tim.`,
    price: 120000,
    coverImage: "/images/books/the-little-prince.jpg",
    isbn: "978-0156012195",
    category: "Khác",
    publishYear: 1943,
    stock: 50,
  },
  {
    id: "20",
    title: "Harry Potter and the Philosopher's Stone",
    author: "J. K. Rowling",
    description: `Câu chuyện bắt đầu khi cậu bé mồ côi Harry Potter khám phá ra mình là phù thủy và được nhận vào Hogwarts – ngôi trường phù thủy danh giá. Tại đây, Harry kết bạn với Ron và Hermione, khám phá bí ẩn chiếc mũ phân loại, trò Quidditch, và sự tồn tại của hòn đá phù thủy hùng mạnh có thể mang lại sinh lực vĩnh hằng. Rowling tạo dựng thế giới phép thuật sống động, với những sinh vật kỳ bí, phép thuật tinh xảo, và xung đột giữa cái thiện và cái ác qua hình tượng Voldermort. “Harry Potter và Hòn đá Phù thủy” không chỉ là khởi đầu cho chuỗi 7 tập, mà còn khơi dậy khát vọng phiêu lưu và tình bạn sâu sắc trong mỗi độc giả.`,
    price: 200000,
    coverImage: "/images/books/harry-potter-1.jpg",
    isbn: "978-0747532699",
    category: "Phép thuật & Phiêu lưu",
    publishYear: 1997,
    stock: 60,
  },
  {
    id: "21",
    title: "Nỗi Buồn Chiến Tranh",
    author: "Bảo Ninh",
    description: `Xuyên suốt tiểu thuyết, K – cựu bộ đội sư đoàn cũng là người kể chuyện – vật lộn với ám ảnh chiến tranh, ký ức về người bạn Tri và mối tình với cô y tá Phương. Cuộc chiến chống Mỹ qua góc nhìn người lính không chỉ là những trận đánh đẫm máu, mà còn là tâm lý tan vỡ, hoang mang và khát khao trở về với cuộc sống bình thường. Bảo Ninh sử dụng lối kể phi tuyến tính, đan xen quá khứ – hiện tại, giấc mơ – thực tại, tạo nên cảm giác mơ hồ, cho độc giả cảm nhận sâu sắc hơn nỗi đau chiến tranh. “Nỗi Buồn Chiến Tranh” được coi là tác phẩm biên niên sử về chiến tranh Việt Nam, khai phá mặt tối của bất cứ cuộc xung đột nào.`,
    price: 120000,
    coverImage: "/images/books/noi-buon-chien-tranh.jpg",
    isbn: "978-6046991238",
    category: "Văn học",
    publishYear: 1991,
    stock: 45,
  },
  {
    id: "22",
    title: "Mắt biếc",
    author: "Nguyễn Nhật Ánh",
    description: `Mắt Biếc là một trong những tiểu thuyết nổi bật nhất của nhà văn Nguyễn Nhật Ánh, người được mệnh danh là “nhà văn của tuổi thơ”. Tác phẩm không chỉ là câu chuyện tình yêu đẹp nhưng đầy bi kịch, mà còn khắc họa sống động vẻ đẹp của làng quê Việt Nam và những giá trị nhân văn sâu sắc. Qua từng trang sách, người đọc sẽ cảm nhận được sự tinh tế trong từng câu chữ và những cảm xúc rung động tận đáy lòng.`,
    price: 77000,
    coverImage: "/images/books/mat-biec.jpg",
    isbn: "978-6049912563",
    category: "Văn học",
    publishYear: 1990,
    stock: 50,
  },
  {
    id: "23",
    title: "Chiến Tranh Giữa Các Vì Sao",
    author: "George Lucas",
    description: `Bối cảnh vũ trụ tương lai, khi nhân loại đã phát triển công nghệ vượt ánh sáng và phân tán khắp thiên hà. Trung úy Orion Lê – phi công hạng B – được giao nhiệm vụ hộ tống đoàn khoa học đến vùng không gian mới. Khi xâm nhập lãnh thổ kẻ thù, anh phát hiện âm mưu sử dụng vũ khí hủy diệt toàn cầu. Song song với các trận giao tranh vũ trụ nghẹt thở, Lê còn phải đương đầu với xung đột nội tâm: niềm tin vào chính nghĩa, tình đồng đội và nỗi ám ảnh mất mát người thân. Tác phẩm pha trộn yếu tố khoa học giả tưởng với triết lý về nhân tính và bản chất chiến tranh.`,
    price: 140000,
    coverImage: "/images/books/chien-tranh-giua-cac-vi-sao.jpg",
    isbn: "978-6049912785",
    category: "Khoa học viễn tưởng",
    publishYear: 2010,
    stock: 30,
  },
  {
    id: "24",
    title: "The Road",
    author: "Cormac McCarthy",
    description: `Trên một hành trình khắc nghiệt qua miền Nam nước Mỹ sau đại họa tận thế, người cha và cậu con trai bước đi giữa hoang tàn của thế giới đã sụp đổ. Với lương thực cạn dần, nhiệt độ hạ thấp, và mối đe dọa đến từ bọn ăn thịt người, họ phải tự vệ bằng cây xẻng, thắp lên những ngọn lửa hy vọng trong màn đêm bất tận. McCarthy khai thác triệt để sự im lặng và khoảng cách giữa các nhân vật để làm nổi bật tình cha con, nhân tính yếu ớt nhưng kiên cường, và khát vọng sinh tồn đến cùng. Ngôn ngữ giản lược, đôi khi chỉ là một vài từ vỡ vụn, càng tô đậm cảm giác hoang mang và tuyệt vọng, nhưng cũng chính ở đó, tình yêu vô điều kiện giữa cha và con trở nên ấm áp và quý giá nhất.`,
    price: 175000,
    coverImage: "/images/books/the-road.jpg",
    isbn: "978-0307387899",
    category: "Hậu tận thế",
    publishYear: 2006,
    stock: 30,
  },
  {
    id: "25",
    title: "Les Misérables",
    author: "Victor Hugo",
    description: `Bắt đầu từ cuộc đời bất hạnh của Jean Valjean – cựu tù khổ sai vì trót ăn cắp một ổ bánh mì nuôi em – Hugo mở ra bức tranh xã hội Pháp đầu thế kỷ 19 với những mâu thuẫn giàu – nghèo, công lý – lòng nhân. Valjean đổi tên, trở thành thị trưởng và công nhân mẫu mực, nhưng luôn bị thanh tra Javert truy đuổi không ngừng. Xen kẽ là số phận của Fantine, Cosette, Marius và cộng đồng sinh viên cách mạng trên gò Barricade. Với những chương tiểu luận về lịch sử Paris, kiến trúc hầm mỏ hay tâm lý người nghèo, “Những người khốn khổ” không chỉ là tiểu thuyết mà còn là bản cáo trạng đanh thép và khúc ca bi tráng về lòng trắc ẩn, hy sinh và khát vọng tự do.`,
    price: 240000,
    coverImage: "/images/books/les-miserables.jpg",
    isbn: "978-0451419439",
    category: "Lịch sử & Xã hội",
    publishYear: 1862,
    stock: 20,
  },
  {
    id: "26",
    title: "Catch-22",
    author: "Joseph Heller",
    description: `Đặt bối cảnh tại một căn cứ không quân Mỹ đảo Địa Trung Hải trong Thế chiến II, “Catch-22” xoay quanh trung úy Yossarian và đồng đội, những người dấn thân vào những phi vụ đầy rẫy sự vô lý. Mỗi khi họ muốn giải ngũ vì sợ chết, điều kiện “Catch-22” lại quy định: chỉ những ai có đủ lý trí mới được yêu cầu bay tiếp, còn ai muốn trở về thì chứng tỏ mình không đủ lý trí. Heller dùng lối viết chồng hồi, đảo trật tự thời gian và chi tiết phi lý để châm biếm chiến tranh, cơ quan hành chính và định chế quân đội. Cảm giác hoang mang, mệt mỏi và cười ra nước mắt hiện lên rõ nét qua từng trang sách.`,
    price: 170000,
    coverImage: "/images/books/catch-22.jpg",
    isbn: "978-1451626650",
    category: "Khác",
    publishYear: 1961,
    stock: 25,
  },
  {
    id: "27",
    title: "Tình Yêu Thời Dịch Tả",
    author: "Gabriel García Márquez",
    description: `Xoay quanh chuyện tình kéo dài hơn nửa thế kỷ của Florentino Ariza và Fermina Daza tại vùng Caribe Nam Mỹ cuối thế kỷ 19. Khi Fermina theo nhà văn trẻ Lorenzo trở về Paris, Florentino đâm ra tuyệt vọng nhưng không từ bỏ: ông trải qua hàng trăm mối tình chóng vánh, nhưng trái tim vẫn khắc khoải chờ đợi cô. Khi Lorenzo Daza qua đời, hai người gặp lại trong một buổi tiệc trên du thuyền; dù nằm giữa đại dương mênh mông, họ nhận ra rằng tình yêu thật sự là “dấu chấm câu cuối cùng” của cuộc đời. Marquez khéo léo đan xen tường thuật thời gian, ký ức và quan niệm về tình cảm, làm nổi bật khát vọng chung thủy và chân thành trước cơn bão của cuộc sống.`,
    price: 210000,
    coverImage: "/images/books/love-in-the-time-of-cholera.jpg",
    isbn: "978-0307389731",
    category: "Lãng mạn",
    publishYear: 1985,
    stock: 28,
  },
  {
    id: "28",
    title: "Wuthering Heights",
    author: "Emily Brontë",
    description: `Trên đồng hoang gió lộng của Yorkshire, mối tình bi kịch giữa Heathcliff – chàng trai được gia đình Earnshaw nhận nuôi – và Catherine Earnshaw bùng cháy như ngọn lửa hoang dại. Sự phản bội và oán hận kéo dài qua hai thế hệ, khi Heathcliff tra tấn tâm hồn những người ông yêu thương và ghét bỏ. Emily Brontë dựng lên một không gian ma mị, nơi tình yêu và hận thù đan xen, khiến con người chịu đựng số phận nghiệt ngã. Dưới lớp ngôn ngữ lãng mạn, tác phẩm còn là nghiên cứu sâu sắc về bản năng, quyền lực và sự hủy diệt của những cảm xúc mãnh liệt.`,
    price: 160000,
    coverImage: "/images/books/wuthering-heights.jpg",
    isbn: "978-0141439556",
    category: "Tiểu thuyết",
    publishYear: 1847,
    stock: 22,
  },
  {
    id: "29",
    title: "Tôi Thấy Hoa Vàng Trên Cỏ Xanh",
    author: "Nguyễn Nhật Ánh",
    description: `Lấy bối cảnh một làng chài miền Trung yên bình, câu chuyện kể qua góc nhìn của cậu bé Thiều và cô bạn Mai. Mùa hè của họ trôi qua với những chuyến đạp xe, bắt ve, và niềm vui giản dị bên những đụn cát vàng rực. Thiều trải nghiệm lần đầu biết đến tình yêu, nỗi ghen tị trước Mai và cậu bạn Khôi, cùng bài học đầu đời về sự trưởng thành và lòng bao dung. Nguyễn Nhật Ánh vẽ nên ký ức tuổi thơ ngọt ngào với ngôn ngữ trong trẻo, giàu hình ảnh, khiến độc giả bồi hồi nhớ về những ngày tháng hồn nhiên mà thiêng liêng nhất.`,
    price: 95000,
    coverImage: "/images/books/toi-thay-hoa-vang-tren-co-xanh.jpg",
    isbn: "978-6049912120",
    category: "Văn học",
    publishYear: 2010,
    stock: 55,
  },
  {
    id: "30",
    title: "Đời Thay Đổi Sau Một Đêm",
    author: "Nguyễn Nhật Ánh",
    description: `Đã bao giờ bạn sống một mình trên hòn đảo hoang giữa mênh mông sóng vỗ? Đã bao giờ bạn thấy những chú cá mập tung tăng bơi lội trong đại dương sâu thẳm ngay dưới chân mình? Đã bao giờ bạn tự tay chăm sóc một chú “sư tử” hiền lành...? Nếu chưa được thử những điều tuyệt vời ấy, bạn hãy thử một lần đặt chân lên “Đảo Mộng Mơ” cùng Nguyễn Nhật Ánh – một cây bút khá quen thuộc với các bạn thiếu nhi – để được trải nghiệm những cảm giác chưa từng có trong đời. “Đảo Mộng Mơ” mang giọng văn nhẹ nhàng, hồn nhiên và ít kịch tính - đúng theo “chất văn Nguyễn Nhật Ánh”. Lấy cảm hứng từ nhân vật Robinson Crusoe, câu chuyện mở đầu bằng việc Tin, một cậu bé lên mười - nhân vật xưng “tôi” nhận ra mình lạc trên một đảo hoang, trong khi cậu chỉ có chai xiro chanh và cuốn truyện. “Đảo” này, thực ra là một đống cát trong sân nhà, nhưng qua trí tưởng tượng của “tiểu Robinson”, thì lại rất đẹp và thơ mộng. Khi còn một mình trên đảo hoang, cậu đã nghĩ ra đủ tình huống có thể xảy ra, và cố tìm cách giải quyết. Dần dần, Bảy - người bạn gần nhà Tin, và Thắm - cô bạn học cùng bàn; cũng quyết định nhảy ra “đại dương” để lên đảo hoang. Và cũng từ giờ phút đó, Tin trở thành Chúa đảo Robinson, Bảy mang tên Thứ Bảy - phó chúa đảo, còn Thắm được phong Chúa đảo phu nhân sau nụ hôn lên má của Tin! Bỗng chốc, chị Hai của Tin, hay Phàn - thằng bé chuyên ăn hiếp mấy đứa nhỏ đã trở thành... hải tặc. Tin ghét mọi người gọi đảo Robinson là “đống cát”, và rất hãnh diện khi được ba tặng cho chiếc ống nhòm để ngắm cảnh và dõi xem có “tàu” nào đến cứu khỏi đảo không. Cuộc sống trên đảo thật là mộng mơ, với ba cô cậu học sinh và một chú “sư tử” tên là Pig (vốn là chú cún của Thắm), dĩ nhiên là sau khi bọn chúng đi học về!`,
    price: 99000,
    coverImage: "/images/books/dao-mong-mo.jpg",
    isbn: "978-6049912340",
    category: "Lãng mạn",
    publishYear: 2012,
    stock: 48,
  },
  {
    id: "31",
    title: "Ngày xưa có một chuyện tình",
    author: "Nguyễn Nhật Ánh",
    description: `Ngày xưa có một chuyện tình, cuốn sách này kể về những câu chuyện tình yêu lãng mạn đầy cảm xúc, với một phong cách viết mới lạ của Nguyễn Nhật Ánh. Từ những tình tiết đơn giản nhưng đầy ý nghĩa, Ngày xưa có một chuyện tình là một tác phẩm khiến độc giả không thể rời mắt khỏi trang sách. Qua từng dòng chữ, độc giả sẽ cảm nhận được hơi thở của tình yêu, những giọt nước mắt và nụ cười trong suốt quãng đời dài. Đây không chỉ là một câu chuyện tình yêu, mà còn là hành trình khám phá bản thân và ý nghĩa của tình yêu đích thực..`,
    price: 105000,
    coverImage: "/images/books/ngay-xua-co-mot-truyen-tinh.jpg",
    isbn: "978-6049912567",
    category: "Khác",
    publishYear: 2016,
    stock: 35,
  },
  {
    id: "32",
    title: "Gánh Hàng Hoa",
    author: "Nguyễn Văn Thọ",
    description: `Tập truyện ngắn xoay quanh cuộc sống của những người bán hoa dạo ven đường Sài Gòn trước 1975. Từ những gánh hàng tấp nập, người đọc gặp gỡ những phận đời: cô Hoa bán nhài, cụ già rụng rời gánh cúc, đến những thiếu nữ lỡ làng theo gánh điệu. Nguyễn Văn Thọ dùng lối kể mộc mạc, chi tiết sinh động và cảm xúc chân thật, khắc họa số phận phụ nữ lao động và nét văn hóa đường phố đặc trưng của Sài Gòn xưa.`,
    price: 90000,
    coverImage: "/images/books/ganh-hang-hoa.jpg",
    isbn: "978-6049912789",
    category: "Văn học",
    publishYear: 1973,
    stock: 40,
  },
  {
    id: "33",
    title: "Bố Già",
    author: "Mario Puzo",
    description: `“Bố Già” (tác phẩm kinh điển của Mario Puzo) là một cuốn sách hay biểu tượng của văn học Mỹ nói về gia đình Mafia Corleone. Cuốn sách kể về cuộc đời và sự nghiệp của Vito Corleone, một ông trùm mafia người Mỹ gốc Ý, cùng với những mâu thuẫn, xung đột và mối quan hệ giữa các thành viên trong đại gia đình của ông. Tiểu thuyết này không chỉ là một bức tranh về thế giới ngầm mafia, mà còn là một nghiên cứu sâu rộng về quyền lực, danh dự, trách nhiệm và tình cảm gia đình trong bộ khung của một xã hội.`,
    price: 140000,
    coverImage: "/images/books/bo-gia.jpg",
    isbn: "978-6049912785",
    category: "Khoa học viễn tưởng",
    publishYear: 2010,
    stock: 30,
  },
  {
    id: "34",
    title: "Mật mã Da Vinci",
    author: "Dan Brown",
    description: `Mật mã Da Vinci là một tác phẩm hay với những tình tiết hấp dẫn, hồi hộp hết sức nhưng không kém thú vị với bao hoàn cảnh vô cùng “ngàn cân treo sợi tóc”. Langdon, một vị giáo sư chuyên nghiên cứu tôn giáo, đang sống một cuộc đời vô cùng yên ổn, bỗng dưng lại rơi vào một trò rượt bắt có thể nguy hiểm đến tính mạng ông. May thay ông lại gặp được Sophie, một người phụ nữ vô cùng thông minh, xinh đẹp và tài năng. Một chuyến đi vô cùng hấp dẫn, trốn chạy gay cấn. Nhờ sự giúp đỡ của Teabing, một nhà sử học tài ba và cũng đầy mưu trí, Langdon và Sophie đã khám phá một chuỗi các sự kiện “không tưởng” một bí mật tưởng chừng như đã lãng quên. `,
    price: 155000,
    coverImage: "/images/books/mat-ma-da-vinci.jpg",
    isbn: "978-0451526342",
    category: "Khác",
    publishYear: 1945,
    stock: 35,
  },
  {
    id: "35",
    title: "Moby-Dick",
    author: "Herman Melville",
    description: `Ishmael lên tàu Pequod với hải tặc Queequeg và trở thành bạn đồng hành với thuyền trưởng Ahab, người bị ám ảnh bởi con cá voi trắng Moby Dick – kẻ đã cướp mất chân ông. Chuyến săn Moby Dick trở thành hành trình trả thù điên dại, xuyên qua Đại Tây Dương, với những cảnh biển khắc nghiệt và cuộc sống trên tàu cá voi của thế kỷ 19. Melville xen lẫn những chương luận bàn về sinh vật học, thần thoại và ngôn ngữ thơ ca, tạo nên một tác phẩm vừa kịch tính vừa triết lý sâu sắc. “Moby‑Dick” không chỉ là câu chuyện săn cá voi, mà còn là minh chứng về lòng kiêu ngạo của con người, sự đối đầu giữa ý chí cá nhân và thiên nhiên bất khuất.`,
    price: 210000,
    coverImage: "/images/books/moby-dick.jpg",
    isbn: "978-1503280786",
    category: "Văn học",
    publishYear: 1851,
    stock: 20,
  },
  {
    id: "36",
    title: "Sống",
    author: "Hải Anh và Pauline Guitton, Hồng Minh dịch",
    description: `Là hiện tượng xuất bản ở Pháp sau khi ra mắt, Sống – cuốn tiểu thuyết đồ họa thực hiện bởi 2 người trẻ - xoay quanh thời gian tham gia chiến khu của một thiếu nữ ở tuổi đôi mươi là một tác phẩm không nên bỏ qua. Được viết dựa trên cuộc đời của nữ đạo diễn Việt Linh tài danh (mẹ của Hải Anh), qua đây ta sẽ được nghe về những kỷ niệm một thời cùng những gian khổ, khó khăn trong những tháng ngày làm đạo diễn của bà. Bên cạnh đó, Hải Anh cũng khắc họa được khoảng cách thế hệ giữa mẹ và mình – 2 người phụ nữ ở 2 thời đại và 2 độ tuổi khác nhau mà bất cứ ai cũng có thể thấy bản thân mình ở đó. Nỗi đau kéo dài bao lâu không quan trọng, mà quan trọng hơn là nhận ra nó và tiến hành thay đổi.`,
    price: 170000,
    coverImage: "/images/books/song.jpg",
    isbn: "978-0140449129",
    category: "Khác",
    publishYear: 2024,
    stock: 28,
  },
  {
    id: "37",
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    description: `Lấy bối cảnh Cách mạng Pháp 1789, câu chuyện song hành giữa London và Paris với các nhân vật Lucie Manette, Charles Darnay và Sydney Carton. Lucie đoàn tụ với cha sau nhiều năm lâm bệnh tâm lý. Darnay – quý tộc Pháp chống lại chế độ hà khắc – trốn sang Anh và yêu Lucie. Carton, luật sư gan lì, âm thầm yêu mến Lucie và sẵn sàng hy sinh. Khi Darnay bị bắt và kết án ở Paris, Carton trao đổi thân phận để chuộc lỗi cho quá khứ. Dickens sử dụng các motif “sự tái sinh” và “mối liên hệ huyết thống” để khắc họa khát khao tự do và tình nghĩa sâu sắc giữa con người trong bối cảnh hỗn loạn xã hội.`,
    price: 165000,
    coverImage: "/images/books/a-tale-of-two-cities.jpg",
    isbn: "978-0141439600",
    category: "Lịch sử cổ điển",
    publishYear: 1859,
    stock: 30,
  },
  {
    id: "38",
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    description: `Alonso Quixano, say mê truyện hiệp sĩ, tự xưng là Don Quixote, đội mũ sắt, cưỡi chiến mã Rocinante và cùng người bạn trung thành Sancho Panza lên đường hành hiệp. Họ gặp gỡ đủ loại người, từ hoàng tử và lính gác, cho đến gió quạt mà Don Quixote tưởng là người khổng lồ khổng lồ. Cervantes vừa châm biếm chủ nghĩa hiệp sĩ lỗi thời, vừa phản ánh bản chất con người qua tình bạn, khát vọng vinh quang và sự ngây thơ của ảo tưởng. Tác phẩm được xem là tiểu thuyết hiện đại đầu tiên, mở ra kỷ nguyên mới cho văn chương phương Tây.`,
    price: 230000,
    coverImage: "/images/books/don-quixote.jpg",
    isbn: "978-0060934347",
    category: "Hài hước",
    publishYear: 1605,
    stock: 18,
  },
  {
    id: "39",
    title: "Tắt Đèn",
    author: "Ngô Tất Tố",
    description: `Huyện lúa Bắc bộ cuối thế kỷ 19, chị Dậu phải chèo chống gia đình khi chồng bị bắt làm nghĩa vụ Triều đình. Để nuôi con, chị gánh gạo đi bán, đối mặt với quan nhiếp chính hà khắc và luật thuế nộ khắc nghiệt. Ngô Tất Tố khắc họa sinh động số phận người nông dân bần cùng, đánh thức ý thức về bất công xã hội qua ngòi bút hiện thực chua xót. “Tắt Đèn” không chỉ là câu chuyện về sự khốn khó, mà còn là bản án đanh thép về chế độ thuế khóa và quyền lực áp bức thời Pháp thuộc.`,
    price: 95000,
    coverImage: "/images/books/tat-den.jpg",
    isbn: "978-6046991258",
    category: "Văn học",
    publishYear: 1939,
    stock: 42,
  },
  {
    id: "40",
    title: "Chiếc Thuyền Ngoài Xa",
    author: "Nguyễn Minh Châu",
    description: `Qua ống kính nhiếp ảnh gia Phùng trên bãi biển miền Trung, cảnh chiếc thuyền lưới căng buồm trước bình minh hiện lên như tác phẩm nghệ thuật. Song khi ông tiếp cận, ông phát hiện một gia đình đánh cá sống trong bạo hành: người chồng vũ phu đánh đập vợ con. Nguyễn Minh Châu đã tạo nên lớp nghĩa đối lập giữa vẻ đẹp nghệ thuật và thực tại khắc nghiệt, đặt ra vấn đề về trách nhiệm của nghệ sĩ trước nỗi đau của nhân dân. “Chiếc Thuyền Ngoài Xa” khơi gợi suy ngẫm về đạo đức, nghệ thuật và trách nhiệm xã hội.`,
    price: 88000,
    coverImage: "/images/books/chiec-thuyen-ngoai-xa.jpg",
    isbn: "978-6049912604",
    category: "Văn học",
    publishYear: 1983,
    stock: 37,
  },
  {
    id: "41",
    title: "Gió Lộng",
    author: "Nguyễn Tú",
    description: `Một tập truyện ngắn với các chủ đề tình yêu, cuộc sống đô thị và ký ức chiến tranh. Nguyễn Tú phác họa chân thực đời sống Sài Gòn sau giải phóng: từ quán cà phê vỉa hè, những khu nhà ổ chuột đến căn hộ cao cấp. Mỗi câu chuyện là một cơn gió lộng qua tâm hồn nhân vật: cô giáo về hưu nhớ lớp xưa, anh công nhân xuống biển tìm cảm hứng, và những đứa trẻ mồ côi trong chung cư. Giọng văn nhẹ nhàng, giàu hình ảnh, “Gió Lộng” đem đến cái nhìn đa chiều về xã hội Việt Nam muôn mặt.`,
    price: 99000,
    coverImage: "/images/books/gio-long.jpg",
    isbn: "978-6049912901",
    category: "Khác",
    publishYear: 2005,
    stock: 33,
  },
  {
    id: "42",
    title: "Bến Không Chồng",
    author: "Duyên Anh",
    description: `Tác phẩm kể chuyện 10 cô gái miền đồng bằng sông Cửu Long phải chịu đựng cảnh “không chồng” khi chồng đi lính thời chống Mỹ. Qua lá thư và nhật ký, họ chia sẻ nỗi cô đơn, lo lắng và hy vọng ngày đoàn tụ. Duyên Anh thể hiện sâu sắc tâm lý phụ nữ nông thôn, với những chi tiết về phong tục, lễ hội và đời sống gia đình. “Bến Không Chồng” vừa là bức chân dung tình yêu thủy chung, vừa là bản trường ca về sự dũng cảm và kiên cường của những người ở hậu phương.`,
    price: 102000,
    coverImage: "/images/books/ben-khong-chong.jpg",
    isbn: "978-6049913021",
    category: "Văn học",
    publishYear: 1975,
    stock: 29,
  },
  {
    id: "43",
    title: "Tuổi Trẻ Đáng Giá Bao Nhiêu",
    author: "Rosie Nguyễn",
    description: `Cuốn sách kết hợp tự truyện và tiểu luận, Rosie Nguyễn – travel blogger nổi tiếng – chia sẻ hành trình tìm kiếm giá trị bản thân qua những chuyến đi, thất bại và giây phút “vỡ òa”. Bài học về đam mê, tính kỷ luật và lòng biết ơn được đan xen cùng những câu chuyện từ khắp châu Á. Tác giả khuyến khích độc giả dám ước mơ, đầu tư cho bản thân và sống trọn vẹn từng khoảnh khắc, vì tuổi trẻ chỉ đến một lần trong đời.`,
    price: 120000,
    coverImage: "/images/books/tuoi-tre-dang-gia-bao-nhieu.jpg",
    isbn: "978-6049913304",
    category: "Kĩ năng sống",
    publishYear: 2018,
    stock: 40,
  },
  {
    id: "44",
    title: "Trên đỉnh giời",
    author: "Y Ban",
    description: `Trong văn đàn Việt, Y Ban luôn được mệnh danh là cây bút nữ cá tính và đầy tinh quái. Gồm gần 20 truyện ngắn, Trên đỉnh giời tiếp tục cho thấy tài năng đặc biệt của bà ở nhiều đề tài, trong đó mảng viết về thân phận người phụ nữ trong thời chiến, trong xã hội đương đại cũng như trong những cuộc tình chếnh choáng vẫn là chủ điểm đáng quan tâm nhất. Bà cho thấy bản thân không ngại bất cứ đề tài gì, dù là miền núi hay là miền xuôi, dù là nông thôn hay thành thị, dù là bi kịch hay là hài kịch, dù là hiện thực hay là huyễn tưởng… thì không có gì cản ngăn được bà. Tính dân gian trong các tác phẩm cũng là một điểm nhấn quan trọng và rất đáng chú ý..`,
    price: 150000,
    coverImage: "/images/books/tren-dinh-gioi.jpg",
    isbn: "978-0156453806",
    category: "Văn học",
    publishYear: 2024,
    stock: 30,
  },
];

export const getInitialBooks = (): Book[] => {
  return JSON.parse(JSON.stringify(initialBooks));
};
