import {
  Order,
  OrderStatus,
  PaymentMethod,
  PaymentStatus,
} from "../types/order";

// Mock order data
export const initialOrders: Order[] = [
  {
    id: "order1",
    userId: "1",
    items: [
      {
        id: "item1",
        bookId: "1",
        quantity: 2,
        unitPrice: 12.99,
        totalPrice: 25.98,
      },
      {
        id: "item2",
        bookId: "3",
        quantity: 1,
        unitPrice: 18.95,
        totalPrice: 18.95,
      },
    ],
    status: OrderStatus.DELIVERED,
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-03-18"),
    shippingAddress: {
      fullName: "John Customer",
      addressLine1: "123 Main St",
      city: "Anytown",
      state: "CA",
      postalCode: "12345",
      country: "USA",
      phoneNumber: "555-123-4567",
    },
    billingAddress: {
      fullName: "John Customer",
      addressLine1: "123 Main St",
      city: "Anytown",
      state: "CA",
      postalCode: "12345",
      country: "USA",
      phoneNumber: "555-123-4567",
    },
    shippingMethod: "Standard Shipping",
    trackingNumber: "TRACK123456789",
    subtotal: 44.93,
    tax: 3.59,
    shippingCost: 4.99,
    discount: 0,
    total: 53.51,
    payment: {
      method: PaymentMethod.CREDIT_CARD,
      status: PaymentStatus.COMPLETED,
      transactionId: "txn_123456789",
      paidAt: new Date("2024-03-15"),
    },
    orderDate: new Date("2024-03-15").toISOString(),
  },
  {
    id: "order2",
    userId: "1",
    items: [
      {
        id: "item3",
        bookId: "5",
        quantity: 1,
        unitPrice: 16.99,
        totalPrice: 16.99,
      },
    ],
    status: OrderStatus.PROCESSING,
    createdAt: new Date("2024-04-20"),
    updatedAt: new Date("2024-04-21"),
    shippingAddress: {
      fullName: "John Customer",
      addressLine1: "123 Main St",
      city: "Anytown",
      state: "CA",
      postalCode: "12345",
      country: "USA",
      phoneNumber: "555-123-4567",
    },
    billingAddress: {
      fullName: "John Customer",
      addressLine1: "123 Main St",
      city: "Anytown",
      state: "CA",
      postalCode: "12345",
      country: "USA",
      phoneNumber: "555-123-4567",
    },
    shippingMethod: "Express Shipping",
    subtotal: 16.99,
    tax: 1.36,
    shippingCost: 9.99,
    discount: 0,
    total: 28.34,
    payment: {
      method: PaymentMethod.PAYPAL,
      status: PaymentStatus.COMPLETED,
      transactionId: "txn_987654321",
      paidAt: new Date("2024-04-20"),
    },
    orderDate: new Date("2024-04-20").toISOString(),
  },
  {
    id: "order3",
    userId: "5",
    items: [
      {
        id: "item4",
        bookId: "2",
        quantity: 1,
        unitPrice: 14.99,
        totalPrice: 14.99,
      },
      {
        id: "item5",
        bookId: "4",
        quantity: 1,
        unitPrice: 22.5,
        totalPrice: 22.5,
      },
      {
        id: "item6",
        bookId: "6",
        quantity: 1,
        unitPrice: 19.99,
        totalPrice: 19.99,
      },
    ],
    status: OrderStatus.SHIPPED,
    createdAt: new Date("2024-04-25"),
    updatedAt: new Date("2024-04-27"),
    shippingAddress: {
      fullName: "Sarah Customer",
      addressLine1: "456 Oak Ave",
      city: "Othertown",
      state: "NY",
      postalCode: "67890",
      country: "USA",
      phoneNumber: "555-987-6543",
    },
    billingAddress: {
      fullName: "Sarah Customer",
      addressLine1: "456 Oak Ave",
      city: "Othertown",
      state: "NY",
      postalCode: "67890",
      country: "USA",
      phoneNumber: "555-987-6543",
    },
    shippingMethod: "Standard Shipping",
    trackingNumber: "TRACK987654321",
    subtotal: 57.48,
    tax: 4.6,
    shippingCost: 4.99,
    discount: 5.0,
    total: 62.07,
    payment: {
      method: PaymentMethod.CREDIT_CARD,
      status: PaymentStatus.COMPLETED,
      transactionId: "txn_567891234",
      paidAt: new Date("2024-04-25"),
    },
    orderDate: new Date("2024-04-25").toISOString(),
  },
];

// Function to reset the orders to initial state
export const getInitialOrders = (): Order[] => {
  return JSON.parse(JSON.stringify(initialOrders));
};
