import {
  Order,
  OrderStatus,
  PaymentMethod,
  PaymentStatus,
} from "../types/order";

export const initialOrders: Order[] = [
  {
    id: "OD_001",
    userId: "1",
    items: [
      {
        id: "item1",
        bookId: "1",
        quantity: 2,
        unitPrice: 12.99,
        totalPrice: 25.98,
      },
      {
        id: "item2",
        bookId: "3",
        quantity: 1,
        unitPrice: 18.95,
        totalPrice: 18.95,
      },
    ],
    status: OrderStatus.DELIVERED,
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-03-18"),
    shippingAddress: {
      fullName: "Nguyễn Văn A",
      addressLine1: "123, Sơn La, Việt Nam",
      city: "Sơn La",
      state: "Sơn La",
      postalCode: "12345",
      country: "Việt Nam",
      phoneNumber: "0371-123-4567",
    },
    billingAddress: {
      fullName: "Lò Văn C",
      addressLine1: "123, đường A, Sơn La, Việt Nam",
      city: "Sơn La",
      state: "Sơn La",
      postalCode: "12345",
      country: "Việt Nam",
      phoneNumber: "0371-123-4567",
    },
    shippingMethod: "Giao hàng tiêu chuẩn",
    trackingNumber: "TRACK123456789",
    subtotal: 44.93,
    tax: 3.59,
    shippingCost: 4.99,
    discount: 0,
    total: 53.51,
    payment: {
      method: PaymentMethod.CREDIT_CARD,
      status: PaymentStatus.COMPLETED,
      transactionId: "txn_123456789",
      paidAt: new Date("2024-03-15"),
    },
    orderDate: new Date("2024-03-15").toISOString(),
  },
  {
    id: "order2",
    userId: "1",
    items: [
      {
        id: "item3",
        bookId: "5",
        quantity: 1,
        unitPrice: 16.99,
        totalPrice: 16.99,
      },
    ],
    status: OrderStatus.PROCESSING,
    createdAt: new Date("2024-04-20"),
    updatedAt: new Date("2024-04-21"),
    shippingAddress: {
      fullName: "Nguyễn Văn B",
      addressLine1: "123, đường B, Sơn La, Việt Nam",
      city: "Sơn La",
      state: "Sơn La",
      postalCode: "12345",
      country: "Việt Nam",
      phoneNumber: "0371-123-4567",
    },
    billingAddress: {
      fullName: "Lò Văn C",
      addressLine1: "123, đường C, Sơn La, Việt Nam",
      city: "Sơn La",
      state: "Sơn La",
      postalCode: "12345",
      country: "Việt Nam",
      phoneNumber: "0371-123-4567",
    },
    shippingMethod: "Giao hàng nhanh",
    subtotal: 16.99,
    tax: 1.36,
    shippingCost: 9.99,
    discount: 0,
    total: 28.34,
    payment: {
      method: PaymentMethod.PAYPAL,
      status: PaymentStatus.COMPLETED,
      transactionId: "txn_987654321",
      paidAt: new Date("2024-04-20"),
    },
    orderDate: new Date("2024-04-20").toISOString(),
  },
  {
    id: "order3",
    userId: "5",
    items: [
      {
        id: "item4",
        bookId: "2",
        quantity: 1,
        unitPrice: 14.99,
        totalPrice: 14.99,
      },
      {
        id: "item5",
        bookId: "4",
        quantity: 1,
        unitPrice: 22.5,
        totalPrice: 22.5,
      },
      {
        id: "item6",
        bookId: "6",
        quantity: 1,
        unitPrice: 19.99,
        totalPrice: 19.99,
      },
    ],
    status: OrderStatus.SHIPPED,
    createdAt: new Date("2024-04-25"),
    updatedAt: new Date("2024-04-27"),
    shippingAddress: {
      fullName: "Nguyễn Văn D",
      addressLine1: "456, đường D, Sơn La, Việt Nam",
      city: "Sơn La",
      state: "Sơn La",
      postalCode: "67890",
      country: "Việt Nam",
      phoneNumber: "0371-123-4567",
    },
    billingAddress: {
      fullName: "Phạm Thị E",
      addressLine1: "456, đường E, Sơn La, Việt Nam",
      city: "Sơn La",
      state: "Sơn La",
      postalCode: "67890",
      country: "Việt Nam",
      phoneNumber: "0371-123-4567",
    },
    shippingMethod: "Giao hàng tiêu chuẩn",
    trackingNumber: "TRACK987654321",
    subtotal: 57.48,
    tax: 4.6,
    shippingCost: 4.99,
    discount: 5.0,
    total: 62.07,
    payment: {
      method: PaymentMethod.CREDIT_CARD,
      status: PaymentStatus.COMPLETED,
      transactionId: "txn_567891234",
      paidAt: new Date("2024-04-25"),
    },
    orderDate: new Date("2024-04-25").toISOString(),
  },
  {
    id: "order4",
    userId: "7",
    items: [
      {
        id: "item7",
        bookId: "8",
        quantity: 2,
        unitPrice: 15.5,
        totalPrice: 31.0,
      },
      {
        id: "item8",
        bookId: "10",
        quantity: 1,
        unitPrice: 24.99,
        totalPrice: 24.99,
      },
    ],
    status: OrderStatus.PROCESSING,
    createdAt: new Date("2024-05-01"),
    updatedAt: new Date("2024-05-01"),
    shippingAddress: {
      fullName: "Nguyễn Văn F",
      addressLine1: "789, đường F, Sơn La, Việt Nam",
      city: "Sơn La",
      state: "Sơn La",
      postalCode: "60001",
      country: "Việt Nam",
      phoneNumber: "0371-123-4567",
    },
    billingAddress: {
      fullName: "Phạm Thị G",
      addressLine1: "789, đường G, Sơn La, Việt Nam",
      city: "Sơn La",
      state: "Sơn La",
      postalCode: "60001",
      country: "Việt Nam",
      phoneNumber: "0371-123-4567",
    },
    shippingMethod: "Giao hàng tiêu chuẩn",
    subtotal: 55.99,
    tax: 4.48,
    shippingCost: 4.99,
    discount: 0,
    total: 65.46,
    payment: {
      method: PaymentMethod.CREDIT_CARD,
      status: PaymentStatus.COMPLETED,
      transactionId: "txn_12345abcde",
      paidAt: new Date("2024-05-01"),
    },
    orderDate: new Date("2024-05-01").toISOString(),
  },
  {
    id: "order5",
    userId: "8",
    items: [
      {
        id: "item9",
        bookId: "15",
        quantity: 1,
        unitPrice: 32.99,
        totalPrice: 32.99,
      },
    ],
    status: OrderStatus.PROCESSING,
    createdAt: new Date("2024-05-02"),
    updatedAt: new Date("2024-05-02"),
    shippingAddress: {
      fullName: "Nguyễn Văn H",
      addressLine1: "101, đường H, Sơn La, Việt Nam",
      city: "Sơn La",
      state: "Sơn La",
      postalCode: "45601",
      country: "Việt Nam",
      phoneNumber: "0371-123-4567",
    },
    billingAddress: {
      fullName: "Phạm Thị I",
      addressLine1: "101, đường I, Sơn La, Việt Nam",
      city: "Sơn La",
      state: "Sơn La",
      postalCode: "45601",
      country: "Việt Nam",
      phoneNumber: "0371-123-4567",
    },
    shippingMethod: "Giao hàng nhanh",
    subtotal: 32.99,
    tax: 2.64,
    shippingCost: 9.99,
    discount: 5.0,
    total: 40.62,
    payment: {
      method: PaymentMethod.PAYPAL,
      status: PaymentStatus.COMPLETED,
      transactionId: "txn_paypal54321",
      paidAt: new Date("2024-05-02"),
    },
    orderDate: new Date("2024-05-02").toISOString(),
  },
  {
    id: "OD_006",
    userId: "10",
    items: [
      {
        id: "item10",
        bookId: "7",
        quantity: 1,
        unitPrice: 18.49,
        totalPrice: 18.49,
      },
      {
        id: "item11",
        bookId: "9",
        quantity: 1,
        unitPrice: 21.75,
        totalPrice: 21.75,
      },
      {
        id: "item12",
        bookId: "12",
        quantity: 1,
        unitPrice: 16.25,
        totalPrice: 16.25,
      },
    ],
    status: OrderStatus.PROCESSING,
    createdAt: new Date(),
    updatedAt: new Date(),
    shippingAddress: {
      fullName: "Nguyễn Văn J",
      addressLine1: "555, đường J, Sơn La, Việt Nam",
      addressLine2: "Apt 303",
      city: "Sơn La",
      state: "Sơn La",
      postalCode: "98765",
      country: "Việt Nam",
      phoneNumber: "0371-123-4567",
    },
    billingAddress: {
      fullName: "Phạm Thị K",
      addressLine1: "555, đường K, Sơn La, Việt Nam",
      addressLine2: "Apt 303",
      city: "Sơn La",
      state: "Sơn La",
      postalCode: "98765",
      country: "Việt Nam",
      phoneNumber: "0371-123-4567",
    },
    shippingMethod: "Standard Shipping",
    subtotal: 56.49,
    tax: 4.52,
    shippingCost: 4.99,
    discount: 10.0,
    total: 56.0,
    payment: {
      method: PaymentMethod.CREDIT_CARD,
      status: PaymentStatus.COMPLETED,
      transactionId: "txn_cc789456",
      paidAt: new Date(),
    },
    orderDate: new Date().toISOString(),
  },
];

// Function to reset the orders to initial state
export const getInitialOrders = (): Order[] => {
  return JSON.parse(JSON.stringify(initialOrders));
};
